name: 2025-07-07-scipy2025-tutorial-thinking-in-arrays
channels:
  - conda-forge
dependencies:
  - aiohttp
  - awkward
  - fsspec
  - hist
  - jax
  - jaxlib
  - jupyterlab
  - jupyterlab-deck
  - jupyterlab-mathjax3
  - matplotlib
  - mplhep
  - numba
  - numexpr
  - numpy
  - pandas
  - pyarrow
  - python
  - requests
  - scikit-learn
  - scipy
