[workspace]
authors = ["jpivarski <jpivarski@gmail.com>", "pfackeldey <fackeldey.peter@gmail.com>"]
channels = ["conda-forge"]
name = "2025-07-07-scipy2025-tutorial-thinking-in-arrays"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks.start]
cmd = "jupyter lab"

[dependencies]
aiohttp = "*"
awkward = "*"
fsspec = "*"
hist = "*"
jupyterlab = "*"
jupyterlab-deck = "*"
jupyterlab-mathjax3 = "*"
matplotlib = "*"
mplhep = "*"
numba = "*"
numexpr = "*"
numpy = "*"
pandas = "*"
pyarrow = "*"
python = "*"
requests = "*"
scikit-learn = "*"
scipy = "*"

[pypi-dependencies]
jax = "*"